name: Build Kernel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc flex bison libssl-dev \
            libncurses-dev dwarves pahole ccache clang llvm lld

    - name: Configure kernel
      run: make defconfig

    - name: Build kernel
      run: make -j$(nproc)

    - name: Package kernel
      run: make -j$(nproc) bindeb-pkg

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-debs
        path: ../*.deb
